using EcosDelLaberinto.Bootstrap;
using EcosDelLaberinto.Data;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;

namespace EcosDelLaberinto.Editor
{
    /// <summary>
    /// Editor tooling that materialises the in-code <see cref="DefaultContent"/> into real
    /// ScriptableObject assets and a boot scene, so designers can tweak content in the Inspector.
    /// Everything the game needs to run is generated by the two menu items below.
    /// </summary>
    public static class ContentGenerator
    {
        private const string Root = "Assets/_Project";
        private const string SoRoot = Root + "/ScriptableObjects";
        private const string ScenesRoot = Root + "/Scenes";

        [MenuItem("Ecos/Generate Content Assets")]
        public static GameDatabase GenerateContent()
        {
            EnsureFolder(Root, "ScriptableObjects");
            EnsureFolder(SoRoot, "Characters");
            EnsureFolder(SoRoot, "Levels");
            EnsureFolder(SoRoot, "Achievements");

            var config = DefaultContent.BuildConfig();
            CreateOrReplace(config, $"{SoRoot}/GameConfig.asset");

            var db = ScriptableObject.CreateInstance<GameDatabase>();
            db.Config = config;

            foreach (var c in DefaultContent.BuildCharacters())
            {
                CreateOrReplace(c, $"{SoRoot}/Characters/Character_{c.Id}.asset");
                db.Characters.Add(c);
            }

            foreach (var l in DefaultContent.BuildLevels())
            {
                CreateOrReplace(l, $"{SoRoot}/Levels/Level_{l.Id}.asset");
                db.Levels.Add(l);
            }

            foreach (var a in DefaultContent.BuildAchievements())
            {
                CreateOrReplace(a, $"{SoRoot}/Achievements/Achievement_{a.Id}.asset");
                db.Achievements.Add(a);
            }

            db.BuildIndices();
            CreateOrReplace(db, $"{SoRoot}/GameDatabase.asset");

            var audio = ScriptableObject.CreateInstance<EcosDelLaberinto.Audio.AudioLibrary>();
            CreateOrReplace(audio, $"{SoRoot}/AudioLibrary.asset");

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log("[Ecos] Content assets generated under " + SoRoot);
            return db;
        }

        [MenuItem("Ecos/Create Main Scene")]
        public static void CreateMainScene()
        {
            var db = AssetDatabase.LoadAssetAtPath<GameDatabase>($"{SoRoot}/GameDatabase.asset");
            if (db == null)
            {
                db = GenerateContent();
            }

            EnsureFolder(Root, "Scenes");

            var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

            var camGo = new GameObject("Main Camera", typeof(Camera));
            camGo.tag = "MainCamera";
            camGo.transform.position = new Vector3(0, 0, -10f);
            camGo.GetComponent<Camera>().orthographic = true;

            var appGo = new GameObject("GameApp");
            var app = appGo.AddComponent<GameApp>();
            var so = new SerializedObject(app);
            var dbProp = so.FindProperty("_database");
            if (dbProp != null)
            {
                dbProp.objectReferenceValue = db;
            }

            var audio = AssetDatabase.LoadAssetAtPath<EcosDelLaberinto.Audio.AudioLibrary>(
                $"{SoRoot}/AudioLibrary.asset");
            var audioProp = so.FindProperty("_audioLibrary");
            if (audioProp != null)
            {
                audioProp.objectReferenceValue = audio;
            }

            so.ApplyModifiedPropertiesWithoutUndo();

            var path = $"{ScenesRoot}/Main.unity";
            EditorSceneManager.SaveScene(scene, path);
            AddSceneToBuildSettings(path);
            Debug.Log("[Ecos] Main scene created at " + path);
        }

        private static void AddSceneToBuildSettings(string path)
        {
            var scenes = new System.Collections.Generic.List<EditorBuildSettingsScene>(
                EditorBuildSettings.scenes);
            if (scenes.Exists(s => s.path == path))
            {
                return;
            }

            scenes.Insert(0, new EditorBuildSettingsScene(path, true));
            EditorBuildSettings.scenes = scenes.ToArray();
        }

        private static void CreateOrReplace(Object asset, string path)
        {
            var existing = AssetDatabase.LoadAssetAtPath<Object>(path);
            if (existing != null)
            {
                AssetDatabase.DeleteAsset(path);
            }

            AssetDatabase.CreateAsset(asset, path);
        }

        private static void EnsureFolder(string parent, string child)
        {
            if (!AssetDatabase.IsValidFolder($"{parent}/{child}"))
            {
                AssetDatabase.CreateFolder(parent, child);
            }
        }
    }
}
